#!/usr/bin/env python3
# Populate an initrd directory with programs and their libraries
# https://www.kernel.org/doc/Documentation/early-userspace/buffer-format.txt
import sys
import re
import os
import cpiofile
import traceback
import argparse
import subprocess
from tempfile import NamedTemporaryFile

bindir = "bin"
libdir = "lib64"
verbose = False
cwd = '.'
no_strip = False

depsfile = None
deps = ()
cpio = cpiofile.CPIO()

def system(*s):
	# do not close file descriptors, which will allow
	# communication from sub-make invocations to the make
	# that invoked us.  allow failures
	return subprocess.run(s, close_fds=False, capture_output=True)

def die(s):
	print(s, file=sys.stderr)
	exit(1)

def filemode(filename):
	try:
		s = os.stat(filename)
		return s.st_mode
	except Exception as e:
		print(e, file=sys.stderr)
		return None
def exists(f):
	try:
		os.stat(f)
		return True
	except Exception as e:
		return False
def readfile(filename):
	with open(filename, "rb") as f:
		return f.read()

def deps_add(filename):
	if not depsfile:
		return
	if filename in deps:
		return
	deps[filename] = 1
	print("\t" + filename + " \\", file=depsfile)

### try stripping executables and libraries before loading them
def try_strip(filename):
	if no_strip:
		return readfile(filename)

	try:
		with NamedTemporaryFile() as tmp:
			rc = system("strip", "-o", tmp.name, filename)
			if rc.returncode == 0:
				# strip succeeded, use it instead
				return readfile(tmp.name)
	except Exception as e:
		# something went wrong with strip, use the file as is
		return readfile(filename)

def process_line(line):
	words = re.split(r'\s+', line)
	if words[0] == "symlink":
		# the filename is the second part, the data in that
		# file is the path to the real file
		cpio.symlink(words[2], words[1])
		return
	if words[0] == "mkdir":
		mode = 0o777
		if len(words) > 2:
			mode = int(words[2], 8)
		cpio.mkdir(words[1], mode)
		return
	if words[0] == "mknod":
		# mknod path [c|b] major minor
		cpio.mknod(words[1], words[2], words[3], words[4])
		return
	if words[0] == "exec":
		# command line stuff to be read by init
		# exec /init.d/10-module cmd [args...]
		cpio.add(words[1], data=words[2:])
		return

	# normal file
	filename = words[0]
	dest = bindir
	if len(words) > 1:
		dest = words[1]

	# - marks optional files; do not die if they do not exist
	optional = False
	if filename[0] == '-':
		optional = True
		filename = filename[1:]

	# if a relative file name is provided, update it with the cwd
	if filename[0] != '/':
		filename = os.path.join(cwd, filename)

	if optional and not exists(filename):
		print(filename + ": skipping")
		return

	if filename.endswith('/'):
		# recursive directory copy
		olddir = os.path.normpath(filename)

		if len(words) > 2:
			pattern = words[2]
		else:
			# skip editor temp files .*.swp
			pattern = r'\.[^.]*\.sw[po]$'

		if verbose:
			print('walking', olddir)

		for root, dirs, files in os.walk(olddir):
			# strip the non-relative path part
			# is there a better way to do this?
			newroot = os.path.join(dest, os.path.relpath(root, start=olddir))
			cpio.mkdir(newroot)
			for f in files:
				oldname = os.path.join(root, f)
				newname = os.path.join(newroot, f)

				# filter any that match the exclusion pattern
				if re.search(pattern, oldname):
					continue

				cpio.add(newname, data=readfile(oldname))
				deps_add(oldname)

		# ldd is *not* done on recursive directories
		return

	# strip the local path
	dest_filename = os.path.basename(filename)

	cpio.add(dest + "/" + dest_filename, data=try_strip(filename), mode=filemode(filename))
	deps_add(filename)

	deps = system("ldd", filename)
	if deps.returncode != 0:
		return
	if deps.stderr == b'\tnot a dynamic executable\n':
		return

	for dep in deps.stdout.split(b'\n'):
		dep = dep.decode('utf-8')
		dep = re.sub(r'^.* => ', '', dep)
		dep = re.sub(r'^\s*', '', dep)
		lib = dep.split(' ')[0]

		if lib == '' or re.match(r'^linux-vdso', lib):
			continue
		
		# strip the local path and put the library in the libdir
		dest_lib = os.path.basename(lib)
		cpio.add(libdir + "/" + dest_lib, data=try_strip(lib))
		deps_add(filename)

parser = argparse.ArgumentParser()
parser.add_argument('files',
	nargs='+',
	help="Configuration files to parse")
parser.add_argument('-o', '--output',
	dest='cpio', type=str,
	default='-',
	help="Output of the cpio file")
parser.add_argument( '-v', '--verbose',
	dest='verbose', action='store_true',
	help="Log every file included")
parser.add_argument( '-c', '--xz',
	dest='xz', action='store_true',
	help="Compress the initrd with xz")
parser.add_argument('-r', '--relative',
	dest='relative', action='store_true',
	help="Use the path of the config for relative path files")
parser.add_argument('-M', '--deps',
	dest='deps', type=str,
	help="Output dependencies for Makefile rebuilds")
parser.add_argument('--no-strip',
	dest='no_strip', action='store_true',
	help="Do not strip libraries and executables")
parser.add_argument('--add',
	dest='extra', type=str, action='append',
	help="Extra binaries to be included")

args = parser.parse_args()
verbose = args.verbose
cpio.verbose = verbose
initrd_filename = args.cpio
no_strip = args.no_strip

if args.deps:
	depsfile = open(args.deps, "w")
	print("# Autogenerated dependencies for " + initrd_filename, file=depsfile)
	print(initrd_filename + ": \\", file=depsfile)


for filename in args.files:
	if args.relative:
		cwd = os.path.split(filename)[0]
	if cwd == '':
		cwd = '.'

	with open(filename, "r") as f:
		linenum = 0
		for line in f.readlines():
			linenum += 1

			# strip any commands and skip blank lines
			line = re.sub(r'\n$', '', line)
			line = re.sub(r'^\s*', '', line)
			line = re.sub(r'\s*#.*$','', line)
			if len(line) == 0:
				continue

			#print("%s:%d: %s" % (filename, linenum, line))

			try:
				process_line(line)
			except Exception as e:
				print("%s:%d: failed '%s' (cwd=%s)" % (filename, linenum, line, cwd), e, file=sys.stderr)
				print(traceback.format_exc())
				exit(1)

# restore the cwd to the current directory
cwd = '.'
if args.extra:
	for line in args.extra:
		try:
			process_line(line)
		except Exception as e:
			print("%s:%d: failed '%s'" % (filename, linenum, line), e, file=sys.stderr)
			print(traceback.format_exc())
			exit(1)


compressed = args.xz or initrd_filename.endswith('.xz')
image = cpio.tobytes(compressed)

if initrd_filename == '-':
	sys.stdout.buffer.write(image)
else:
	with open(initrd_filename, "wb") as initrd:
		initrd.write(image)
