#!/usr/bin/python3
# build a small initd world
import builder

kbuild_make = [
	"make",
		"-C%(src_dir)s",
		"O=%(rout_dir)s",
		"KBUILD_HOST=builder",
		"KBUILD_USER=%(out_hash)s",
		"KBUILD_BUILD_TIMESTAMP=1970-01-01",
		"KBUILD_BUILD_VERSION=%(src_hash)s",
]

build_dir = "/tmp/builder"

linux = builder.Submodule("linux",
	url = "https://cdn.kernel.org/pub/linux/kernel/v%(major)s.x/linux-%(version)s.tar.xz",
	version = "5.4.117",
	tarhash = "4e989b5775830092e5c76b5cca65ebff862ad0c87d0b58c3a20d415c3d4ec770",
	config_files = [ "config/linux-virtio.config" ],
	configure = [
		"make",
		"-C%(src_dir)s",
		"O=%(rout_dir)s",
		"olddefconfig"
	],
	make = kbuild_make,
)

busybox = builder.Submodule("busybox",
	version = "1.32.0",
	url = "https://busybox.net/downloads/busybox-%(version)s.tar.bz2",
	tarhash = "c35d87f1d04b2b153d33c275c2632e40d388a88f19a9e71727e0bbbff51fe689",
	config_files = [ "config/busybox.config" ],
	patches = [ "patches/busybox-1.28.0.patch" ],
	configure = [
		"make",
		"-C%(src_dir)s",
		"O=%(rout_dir)s",
		"oldconfig"
	],
	make = kbuild_make,
)

util_linux = builder.Submodule("util-linux",
	version		= "2.29.2",
	url		= "https://www.kernel.org/pub/linux/utils/util-linux/v%(major)s.%(minor)s/util-linux-%(version)s.tar.xz",
	tarhash		= "accea4d678209f97f634f40a93b7e9fcad5915d1f4749f6c47bee6bf110fe8e3",
	depends		= [ linux ],
	configure	= [
		"%(src_dir)s/configure",
		"--prefix", "/",
		"--oldincludedir", "%(linux.out_dir)s/include",
		"--without-ncurses",
		"--without-ncursesw",
		"--without-tinfo",
		"--without-udev",
		"--without-python",
		"--disable-bash-completion",
		"--disable-all-programs",
		"--enable-libuuid",
		"--enable-libblkid",
	],
	make = [ "make" ],
)

zlib = builder.Submodule('zlib',
	version = '1.2.11',
	url = 'https://www.zlib.net/zlib-%(version)s.tar.gz',
	tarhash = 'c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1',
	configure = [
		"%(src_dir)s/configure",
		"--prefix=/",
	],
	make = [ "make" ],
)
#zlib_libraries := libz.so.1

kexec = builder.Submodule('kexec',
	version = '2.0.20',
	url = 'https://kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-%(version)s.tar.gz',
	tarhash = 'cb16d79818e0c9de3bb3e33ede5677c34a1d28c646379c7ab44e0faa3eb57a16',
	patches = [ "patches/kexec-2.0.20.patch" ],
	configure = [
		"%(src_dir)s/configure",
		"--host", "i386-elf-linux",
		"--target", "x86_64",
		"--prefix=/",
	],
	depends = [ zlib ],
)
#kexec_output := build/sbin/kexec

build = builder.Builder([kexec, util_linux, linux, busybox])
build.build_all()
