name: Build heads firmware on ubuntu 20.04
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Update image
        run: apt update
      - name: Install dependencies
        run: DEBIAN_FRONTEND=noninteractive apt install -y patch gcc g++ python3 python3-pip python3-requests git texinfo bzip2 xz-utils cmake bc lz4 libssl-dev flex bison m4 rsync wget libelf-dev
      - name: Build package
        run: SINGLE_THREAD=1 CACHE_SERVER=https://v.st/~hudson/cache make -j3 heads

      - name: Upload built coreboot packages
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: |
            build/install/coreboot-*/*/coreboot-*.rom
            build/install/initrd-*/*/*.hashes
