name: Build heads firmware on ubuntu 20.04
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Update image
        run: apt update
      - name: Install dependencies
        run: DEBIAN_FRONTEND=noninteractive apt install -y patch gcc g++ python3 python3-pip python3-requests git texinfo bzip2 xz-utils cmake bc lz4 libssl-dev flex bison m4 rsync wget
      - name: Fix old python
        run: pip3 install graphlib_backport
      - name: Fix cross compiler paths
        run: mkdir -p /root ; ln -s `pwd` /root/linux-builder
      - name: Build package
        run: CACHE_SERVER=https://v.st/~hudson/cache make -j1 heads

      - name: Upload heads packages
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: build/out/coreboot-*/*/coreboot-*.rom
